services:
  preguntados-php:
    container_name: preguntados-php
    build:
      context: .
    user: "1000:1000"
    networks:
      - preguntados
    sysctls:
      - "net.ipv4.ip_unprivileged_port_start=0"
    ports:
      - "80:80"
    environment:
      PREGUNTADOS_AUTORUN_MIGRATIONS: "false"
    volumes:
      - ./:/var/www/html
    restart: unless-stopped
  preguntados-mariadb:
    container_name: preguntados-mariadb
    image: mariadb:latest
    networks:
      - preguntados
    ports:
      - "3307:3306"
    volumes:
      - preguntados-mariadb:/var/lib/mysql
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "true"
      MARIADB_ROOT_PASSWORD: ""

networks:
  preguntados:
    driver: bridge

volumes:
  preguntados-mariadb:
