name: Check PHP Syntax

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-php-syntax:
    name: Check PHP Syntax
    runs-on: ubuntu-latest
    steps:
      -
        name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          # This is the minimum PHP version supported by your project
          php-version: '8.0'
          extensions: opcache
          coverage: none
          tools: none
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Check syntax
        uses: mlocati/check-php-syntax@v1
        with:
          directory: .
          include: |
            src/index.php
          fail-on-warnings: true
