name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deployment:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          extensions: mysqli
          coverage: none
          tools: composer

      - name: Checkout
        uses: actions/checkout@v6

      - name: Controlar sintaxis de PHP
        uses: mlocati/check-php-syntax@v1
        with:
          directory: .
          include: |
            index.php
          fail-on-warnings: true

      - name: Prevenir cambios de SQL
        id: changed-markdown-files
        uses: tj-actions/changed-files@9426d40962ed5378910ee2e21d5f8c6fcbf2dd96 # v47.0.6
        with:
          files: |
            database/*.sql

      - name: Actualizar config.ini
        env:
          DB_HOSTNAME: ${{ secrets.DB_HOSTNAME }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
          SMTP_HOSTNAME: ${{ secrets.SMTP_HOSTNAME }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        run: |
          echo "db_hostname='$DB_HOSTNAME'" > config/config.ini
          echo "db_username='$DB_USERNAME'" >> config/config.ini
          echo "db_password='$DB_PASSWORD'" >> config/config.ini
          echo "db_database='$DB_DATABASE'" >> config/config.ini
          echo "db_automigrate='true'" >> config/config.ini
          echo "smtp_hostname='$SMTP_HOSTNAME'" >> config/config.ini
          echo "smtp_port='$SMTP_PORT'" >> config/config.ini
          echo "smtp_username='$SMTP_USERNAME'" >> config/config.ini
          echo "smtp_password='$SMTP_PASSWORD'" >> config/config.ini
        shell: bash

      - name: Desplegar a Hosting via FTP
        if: ${{ vars.FTP_PROTOCOL != 'sftp' }}
        uses: SamKirkland/FTP-Deploy-Action@v4.4.0
        with:
          protocol: ${{ vars.FTP_PROTOCOL }}
          server: ${{ secrets.FTP_HOSTNAME }}
          port: ${{ secrets.FTP_PORT }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: ${{ secrets.FTP_SERVER_DIR }}
          exclude: |
            **/.git*
            **/.git*/**
            config.ini

      - name: Desplegar a Hosting via SFTP
        if: ${{ vars.FTP_PROTOCOL == 'sftp' }}
        uses: wlixcc/SFTP-Deploy-Action@v1.2.6
        with:
          server: ${{ secrets.FTP_HOSTNAME }}
          port: ${{ secrets.FTP_PORT }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          sftp_only: true
          local_path: ./*
          remote_path: ${{ secrets.FTP_SERVER_DIR }}
          sftpArgs: '-o ConnectTimeout=5'
          rsyncArgs: '--exclude=.git --exclude=*.log --include=public/avatars/default.webp --exclude=public/avatars/*'
