name: Pull Requests

on:
  pull_request:
    branches:
      - main

jobs:
  validar-pull-request:
    name: Validar Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          extensions: mysqli
          coverage: none
          tools: composer

      - name: Checkout
        uses: actions/checkout@v4

      - name: Controlar sintaxis de PHP
        uses: mlocati/check-php-syntax@v1
        with:
          directory: .
          include: |
            index.php
          fail-on-warnings: true

      - name: Prevenir cambios de SQL
        uses: tj-actions/verify-changed-files@a1c6acee9df209257a246f2cc6ae8cb6581c1edf
        with:
          fail-if-changed: true
          files: |
              *.sql
